### ISSUE TITLE
Support for latest

### ISSUE THREAD

**Issue by kfrancis** [simpleinjector/glimpse#2]
Just looking for support for the latest versions.

**Comment by dotnetjunkie** [comment]
I decided not to maintain the Glimpse plugin any longer. The library, however, is still compatible with Simple Injector v5. Unfortunately, the NuGet package was locked onto v4. I uploaded a [new version](https://www.nuget.org/packages/Glimpse.SimpleInjector/2.0.1) that contains the exact same dll, but removes the version constraint from the NuGet package.

I hope this works out for you.

**Comment by kfrancis** [comment]
Perfect, that'll do. Thanks @dotnetjunkie!
